language: python
python:
 - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
     - g++-6
     - bash
     - colordiff
     - coreutils
     - graphviz
     - inkscape
     - make

before_install:
 - source ./.github/travis/common.sh

install:
 - stdbuf -i0 -o0 -e0 ./.github/travis/install.sh
 - mkdir .tmp
 - curl -L https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip -o .tmp/ninja-linux.zip
 - unzip .tmp/ninja-linux.zip -d .tmp

before_script:
  - export PATH=$PATH:$PWD/.tmp

script:
  # ping stdout every 9 minutes or Travis kills build
  # https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
 - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
 - stdbuf -i0 -o0 -e0 ./.github/travis/script.sh

after_success:
 - stdbuf -i0 -o0 -e0 ./.github/travis/after_success.sh

after_failure:
 - stdbuf -i0 -o0 -e0 ./.github/travis/after_failure.sh
