language: python
python:
 - "3.6"

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
     - g++-8
     - bash
     - colordiff
     - coreutils
     - graphviz
     - inkscape
     - make
     - cmake

before_install:
 - source ./.github/travis/common.sh

install:
 - stdbuf -i0 -o0 -e0 ./.github/travis/install.sh
 - export PATH=/usr/bin:$PATH
script:
  # ping stdout every 9 minutes or Travis kills build
  # https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
 - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
 - stdbuf -i0 -o0 -e0 ./.github/travis/script_travis.sh

after_success:
 - stdbuf -i0 -o0 -e0 ./.github/travis/after_success.sh

after_failure:
 - stdbuf -i0 -o0 -e0 ./.github/travis/after_failure.sh
