name: symbiflow_arch_def_base
channels:
  - defaults
  - symbiflow
  - conda-forge
dependencies:
  - symbiflow-yosys=0.8_6021_gd8b2d1a2=20200708_083630
  - symbiflow-yosys-plugins=1.0.0.7_0060_g7454cd6=20200902_114536
  - symbiflow-vtr=8.0.0.rc2_5097_gf1a3bcc2a=20200916_072439
  - zachjs-sv2v=0.0.5_0018_ga170536
  - surelog=0.0_1568_ga91fb8ce
  - cmake
  - make
  - openocd
  - flake8
  - nodejs
  - libiconv
  - iverilog
  - libxml2=2.9.10=20200629_180127
  - icestorm
  - capnproto-java
  - pip
  - pip:
    - -r file:requirements.txt
    # Ibex dependencies
    - git+https://github.com/lowRISC/edalize.git@ot
    - git+https://github.com/lowRISC/fusesoc.git@ot
    - mako
