name: symbiflow_arch_def_base
channels:
  - defaults
  - symbiflow
  - quicklogic-corp/label/ql
dependencies:
  - yosys=0.8.0_0002_gc3b38fdc=20200901_073908
  - yosys-plugins=1.2.0_0009_g9ab211c=20201001_121833
  - symbiflow-vtr=8.0.0.rc2_5097_gf1a3bcc2a=20200916_072439
  - zachjs-sv2v=0.0.5_0018_ga170536
  - cmake
  - make
  - openocd
  - flake8
  - nodejs
  - libiconv
  - iverilog
  # libxml2 2.9.10 contains an integer overflow fix required for arch-defs.
  - libxml2>=2.9.10
  - icestorm
  - capnproto-java
  - pip
  - pip:
    - -r file:requirements.txt
    # Ibex dependencies
    - git+https://github.com/lowRISC/edalize.git@ot
    - git+https://github.com/lowRISC/fusesoc.git@ot
    - mako
