name: symbiflow_arch_def_base
channels:
  - defaults
  - symbiflow
dependencies:
  - symbiflow-yosys=0.8_6021_gd8b2d1a2=20200708_083630
  - symbiflow-yosys-plugins=1.0.0.7_0048_gaa1b583=20200706_223638
  - symbiflow-vtr=8.0.0.rc2_4003_g8980e4621=20200720_145630
  - zachjs-sv2v=0.0.5_0004_g5161a9e
  - cmake
  - make
  - openocd
  - flake8
  - nodejs
  - libiconv
  - iverilog
  - libxml2=2.9.10=20200629_180127
  - icestorm
  - pip
  - pip:
    - -r file:requirements.txt
