name: symbiflow_arch_def_base
channels:
  - defaults
  - litex-hub
dependencies:
  - litex-hub::capnproto-java=0.1.5_0012_g44a8c1e=20201104_165332
  - litex-hub::gcc-riscv64-elf-newlib=9.2.0=20201119_154229
  - litex-hub::icestorm=0.0_0719_g792cef0=20201120_145821
  - litex-hub::iverilog=s20150603_0957_gad862020=20201120_145821
  - litex-hub::openocd=0.10.0_1514_ga8edbd020=20201119_154304
  - litex-hub::symbiflow-yosys-plugins=1.0.0_7_g59ff1e6_23_g3a95697_17_g00b887b_0194_g40efa51=20201120_145821
  - litex-hub::prjxray-tools=0.1_2697_g0f939808=20201120_145821
  - litex-hub::prjxray-db=v0.0_245_ge7663ba=20210209_144911
  - litex-hub::vtr-optimized=v8.0.0_3049_g64d15e2dd=20201217_025303
  - litex-hub::yosys=0.9_5007_g2116c585=20201202_112618
  - litex-hub::zachjs-sv2v=0.0.5_0025_ge9f9696=20201120_205532
  - cmake
  - make
  - flake8
  - nodejs
  - libiconv
  # swig is required to build the rapidyaml package
  # It can be removed once that is available in PyPi
  - swig
  # libxml2 2.9.10 contains an integer overflow fix required for arch-defs.
  - libxml2>=2.9.10
  # openjdk, libuuid, pkg-config, and cython are required to build the fasm package's ANTLR backend.
  # They can be removed if fasm is packaged as a binary e.g. a wheel or Conda package.
  - openjdk
  - libuuid
  - pkg-config
  - cython
  - pip
  - pip:
    - -r file:requirements.txt
